#!/bin/bash

echo "overclocking..."

# you must run this (done through install) for overclocking to run, separate screens is optional
#nvidia-xconfig --allow-empty-initial-configuration --enable-all-gpus --cool-bits=28 --separate-x-screens
# you NEED to edit the xorg.conf to FIX this command (bits options line which is wrongly put in screens, should be devices section)
# I added these 2 lines to each device section
# Option         "Coolbits" "31"
# Option         "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x1"

DISPLAY=:0   

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

export NO_AT_BRIDGE="1"


if [ "$HOSTNAME" != "barbara" ]; then
	echo "Please customize overclock with your rig names... and devices"
	exit 1
fi


# sudo nvidia-smi -pm ENABLED

# this is for 1070ti and 1080

FANSPEED_1070=85
FANSPEED_1080=75

POWLIM_1070=170
POWLIM_1080=180

CLOCKOFFSET_1070=125
CLOCKOFFSET_1080=125
#CLOCKOFFSET_1070=100
#CLOCKOFFSET_1080=100


#MEMOFFSET_1070=1000
#MEMOFFSET_1080=1000
MEMOFFSET_1070=1350
MEMOFFSET_1080=1420

VOLTOFFSET_1080=16000

#########################################################
# FANS ##################################################   



nvidia-settings -V \
	-a "[gpu:0]/GPUFanControlState=1" \
	-a "[gpu:1]/GPUFanControlState=1" \
	-a "[gpu:2]/GPUFanControlState=1" \
	-a "[gpu:3]/GPUFanControlState=1" \
	-a "[gpu:4]/GPUFanControlState=1" \
	-a "[gpu:5]/GPUFanControlState=1" \
	-a "[gpu:6]/GPUFanControlState=1"

nvidia-settings -V \
	-a "[fan:0]/GPUTargetFanSpeed=$FANSPEED_1070" \
	-a "[fan:1]/GPUTargetFanSpeed=$FANSPEED_1080" \
	-a "[fan:2]/GPUTargetFanSpeed=$FANSPEED_1080" \
	-a "[fan:3]/GPUTargetFanSpeed=$FANSPEED_1080" \
	-a "[fan:4]/GPUTargetFanSpeed=$FANSPEED_1080" \
	-a "[fan:5]/GPUTargetFanSpeed=$FANSPEED_1080" \
	-a "[fan:6]/GPUTargetFanSpeed=$FANSPEED_1080"

    
#########################################################
# POWER LIMITS ##########################################   

sudo nvidia-smi -i 0 -pl $POWLIM_1070
sudo nvidia-smi -i 1,2,3,4,5,6 -pl $POWLIM_1080


#########################################################
# OVERCLOCK #############################################


# not supported
#nvidia-smi -i 1,2,3,4,5,6 -ac 5005,1911

# not supported
#nvidia-settings -a "[gpu:1]/GPUOverVoltageOffset=$VOLTOFFSET_1080" \
#	-a "[gpu:2]/GPUOverVoltageOffset=$VOLTOFFSET_1080" \
#	-a "[gpu:3]/GPUOverVoltageOffset=$VOLTOFFSET_1080" \
#	-a "[gpu:4]/GPUOverVoltageOffset=$VOLTOFFSET_1080" \
#	-a "[gpu:5]/GPUOverVoltageOffset=$VOLTOFFSET_1080" \
#	-a "[gpu:6]/GPUOverVoltageOffset=$VOLTOFFSET_1080" 


nvidia-settings -V \
	-a "[gpu:0]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1070"    \
	-a "[gpu:1]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	-a "[gpu:2]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	-a "[gpu:3]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	-a "[gpu:4]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	-a "[gpu:5]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	-a "[gpu:6]/GPUGraphicsClockOffset[2]=$CLOCKOFFSET_1080"    \
	\
	-a "[gpu:0]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1070" \
	-a "[gpu:1]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080" \
	-a "[gpu:2]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080" \
	-a "[gpu:3]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080" \
	-a "[gpu:4]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080" \
	-a "[gpu:5]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080" \
	-a "[gpu:6]/GPUMemoryTransferRateOffset[2]=$MEMOFFSET_1080"


nvidia-settings -V \
	-a "[gpu:0]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1070"    \
	-a "[gpu:1]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	-a "[gpu:2]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	-a "[gpu:3]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	-a "[gpu:4]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	-a "[gpu:5]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	-a "[gpu:6]/GPUGraphicsClockOffset[3]=$CLOCKOFFSET_1080"    \
	\
	-a "[gpu:0]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1070" \
	-a "[gpu:1]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080" \
	-a "[gpu:2]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080" \
	-a "[gpu:3]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080" \
	-a "[gpu:4]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080" \
	-a "[gpu:5]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080" \
	-a "[gpu:6]/GPUMemoryTransferRateOffset[3]=$MEMOFFSET_1080"


echo "done overclocking..."
