#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################



# this is for 1070ti and 1080

export FANSPEED_1070=85
export FANSPEED_1080_1=75
export FANSPEED_1080_2=90
export FANSPEED_1080_3=90
export FANSPEED_1080ti=80

export POWLIM_1070=145
export POWLIM_1080_1=160
export POWLIM_1080_2=140
export POWLIM_1080_3=145
export POWLIM_1080ti=200

export CLOCKOFFSET_1070=110
export CLOCKOFFSET_1080_1=125
export CLOCKOFFSET_1080_2=115
export CLOCKOFFSET_1080_3=115
export CLOCKOFFSET_1080ti=135

export MEMOFFSET_1070=1325
export MEMOFFSET_1080_1=1500
export MEMOFFSET_1080_2=1300
export MEMOFFSET_1080_3=1300
export MEMOFFSET_1080ti=1700


export VOLTOFFSET_1080=16000



################################################################################

source $SCRIPT_DIR/OVERCLOCK
