#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################



# this is for 1070ti and 1080

export FANSPEED_1070=75
export FANSPEED_1080=50
export FANSPEED_10802=90
export FANSPEED_1080ti=60

export POWLIM_1070=155
export POWLIM_1080=165
export POWLIM_10802=150
export POWLIM_10803=155
export POWLIM_1080ti=200

export CLOCKOFFSET_1070=110
export CLOCKOFFSET_1080=125
export CLOCKOFFSET_10802=110
export CLOCKOFFSET_1080ti=125

export MEMOFFSET_1070=1325
export MEMOFFSET_1080=1500
export MEMOFFSET_10802=1300
export MEMOFFSET_1080ti=1600


export VOLTOFFSET_1080=16000



################################################################################

source $SCRIPT_DIR/OVERCLOCK
