#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################


# this is for 1070ti and 1080

FANSPEED_1070=40
FANSPEED_1080=40
FANSPEED_10802=40
FANSPEED_1080ti=40

POWLIM_1070=160
POWLIM_1080=170
POWLIM_10802=150
POWLIM_10803=155
POWLIM_1080ti=180

CLOCKOFFSET_1070=0
CLOCKOFFSET_1080=0
CLOCKOFFSET_10802=0
CLOCKOFFSET_1080ti=0

MEMOFFSET_1070=0
MEMOFFSET_1080=0
MEMOFFSET_10802=0
MEMOFFSET_1080ti=0


VOLTOFFSET_1080=16000



################################################################################

source $SCRIPT_DIR/OVERCLOCK
