#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################


# this is for 1070ti and 1080

export FANSPEED_1070=40
export FANSPEED_1080_1=40
export FANSPEED_1080_2=40
export FANSPEED_1080_3=40
export FANSPEED_1080ti=40

export POWLIM_1070=160
export POWLIM_1080_1=170
export POWLIM_1080_2=150
export POWLIM_1080_3=155
export POWLIM_1080ti=180

export CLOCKOFFSET_1070=0
export CLOCKOFFSET_1080_1=0
export CLOCKOFFSET_1080_2=0
export CLOCKOFFSET_1080_3=0
export CLOCKOFFSET_1080ti=0

export MEMOFFSET_1070=0
export MEMOFFSET_1080_1=0
export MEMOFFSET_1080_2=0
export MEMOFFSET_1080_3=0
export MEMOFFSET_1080ti=0


export VOLTOFFSET_1080=16000



################################################################################

source $SCRIPT_DIR/OVERCLOCK
