#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################


# this is for 1070ti and 1080

export FANSPEED_1070=60
export FANSPEED_1080_1=55
export FANSPEED_1080_2=50
export FANSPEED_1080_3=50
export FANSPEED_1080ti=50

export POWLIM_1070=160
export POWLIM_1080_1=170
export POWLIM_1080_2=150
export POWLIM_1080_3=155
export POWLIM_1080ti=180

export CLOCKOFFSET_1070=100
export CLOCKOFFSET_1080_1=100
export CLOCKOFFSET_1080_2=100
export CLOCKOFFSET_1080_3=100
export CLOCKOFFSET_1080ti=100

export MEMOFFSET_1070=100
export MEMOFFSET_1080_1=100
export MEMOFFSET_1080_2=100
export MEMOFFSET_1080_3=100
export MEMOFFSET_1080ti=100

export VOLTOFFSET_1080=16000



################################################################################

source $SCRIPT_DIR/OVERCLOCK
