#!/bin/bash
# author = Jaysunn

# Log
LOGFILE=/var/log/load_kill_log

# log the process causing the load at the time.
PSFILE=/var/log/ps_log

# Obtain the server load
loadavg=`uptime |cut -d , -f 4|cut -d : -f 2`
thisloadavg=`echo $loadavg|awk -F \. '{print $1}'`

if [ "$thisloadavg" -ge "7" ]; then

ps auxfww >> $PSFILE
date >> $LOGFILE

# Issue the command of choice.  This can be any shell command.
## Put the command which restarts ..
reboot

fi

