#!/bin/bash

################################################################################
### SCRIPT_DIR is the location the script
SCRIPT_DIR="`dirname \"$0\"`"                 # relative
SCRIPT_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_DIR" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        exit 1  # fail
fi


################################################################################

LIST=$(cat /var/log/mined.log | cut -d ' ' -f1 | sort | uniq)


for i in $LIST
do
	$SCRIPT_DIR/totalTime $i  
done



