#!/bin/bash

echo "*** updating ***"
cd ~ && updateRec
cd /crypto && updateSubdirs


echo "miners:"
cd /crypto/miners && updateSubdirs

echo ""
echo "*** checking status ***"

echo "tools:"
cd /crypto/tools && git status -s

if [ -d "~/env" ]; then
	echo "env:"
	cd ~/env && git status -s
fi


